#! user/bin/python3
 
# 问题： 
     线性回归的 python 代码
     获得 logistics 回归分析的结果

# 重点：
     f检验 t检验，检测特征值。 https://www.zhihu.com/question/27367177
     分类和预测是预测问题的两种主要模型，分类时预测分类标号，预测是建立连续型函数模型
     分类是构造分类模型，输入样本属性值，输出对应类别，将样本映射到预先定义号的类别。属于有监督学习
     预测是建立两种或以上变量之间相互依赖的函数模型，进行预测或控制
     线性回归相对简单，当因变量和自变量存在某种曲线关系，需要建立非线性回归模型
     logistics 属于概率型非线性回归。分为二分类和多分类。二分类是，y 取0或者1。p为y取1时发生的概率
          研究的是 p 与自变量 x 的关系 
          in(p/1-p) = z =g(x)=β+β1x1+β2x2+... βnxn
          p = P(y=1 |X) = 1/(1+e^-g(x))
          回归系数，即斜率，β是回归系数
          a.iloc[1:3,:3]，前面分割行，后面分割列
          a.iloc[:,:3].as_matrix()，将pd变成 array 矩阵
          data.columns[rlr.get_support()]  index 与 数组结合 b = np.array([False, True,  True]) a[b]
          print(u'有效特征为：%s' % ','.join(['1','2','3'])) 格式化join


          
          
